zil_config:
  zil_api: https://api.zilliqa.com
  zil_chain_id: 111
  zil_message_version: 1
  zil_force_height: 0
  zil_monitor_interval: 10
  zil_headers_per_batch: 2
  corss_chain_manager_address: zil1tjru7m5zdn3x6k0t72nzmmpz62e5qds62nte9t
  cross_chain_manager_proxy_address: zil1n7wkwr0xxslwsrhnqtjrwlus80dp5ncnlpaw93
  side_chain_id: 85
  key_store_path: zilliqa.wallet
  max_exist_tx_epoch: 5
  key_store_pwd_set:
    6c89b62d65dc632e259b96f7ae2f1d68a27e3383: ""
poly_config:
  poly_wallet_file: poly.wallet
  poly_wallet_pwd:
  poly_start_height: 0
  poly_monitor_interval: 2
  entrance_contract_address: "0300000000000000000000000000000000000000"
  rest_url: http://poly.com
target_contracts: target_contracts.json
remove_db: false