name: CI - Release

on:
  push:

jobs:
  release-image:
    permissions:
      id-token: write
      contents: write
    runs-on: docker
    steps:
      - name: 'Checkout scm ${{ inputs.commitOrTag }}'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.commitOrTag }}

      - name: Image tag
        id: set-tag
        run: echo "tag=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Docker images
        run: docker build -t zilliqa/zilliqa-relayer:experimental-${{ steps.set-tag.outputs.tag }} -t zilliqa/zilliqa-relayer:latest .
        shell: bash

      - name: Login to the DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker images to Dockerhub
        if: github.actor != 'dependabot[bot]' && github.ref_name == 'main'
        run: |
          docker push zilliqa/zilliqa-relayer:experimental-${{ steps.set-tag.outputs.tag }}
          docker push zilliqa/zilliqa-relayer:latest
        shell: bash